### ISSUE TITLE
tools/build: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by XEN486** [freewilll/linux-evocation#2]
I am running on windows 10 with wsl compiling this, it seems that everything is fine until it hits this point

**Comment by freewilll** [comment]
I've never tried this on WSL under Windows. Although I think it's just plain old ubuntu, right? I wonder if something is going wrong from a cross compilation point of view. The way I got it working under MacOS is that the Makefile detects the OS like this:

```
ifeq ($(OS), Darwin)
CROSS_COMPILE 	?=i386-elf-
endif
```
Can you post more of a log, so I can see what's going on?

What happens if you run `CROSS_COMPILE="i386-elf-" make`?

**Comment by XEN486** [comment]
sorry for replying so late, I will try, I do have an i386-elf crosscompiler actually!

**Comment by XEN486** [comment]
I get an `i386-elf-gcc: error: language c++ not recognized` error, my crosscompiler was only compiled for C..

**Comment by XEN486** [comment]
if I remove the -x c++ flag, it compiles but then again fails with the Exec format error??

**Comment by freewilll** [comment]
To be honest, I think the project needs some work. I wrote this back in 2017 using Ubuntu 16.04 when it was possible to compile and run 32-bit code on MacOS. It no longer works on my current Mac. It also doesn't compile under Ubuntu 20.04. It makes it even more interesting that you are trying to compile it under windows WSL, something I've never done before.

I just had a go in making it compile under linux 20.04. I pushed some updates to the `2023-revamp` branch which makes it compile. However, when I try and run it, qemu triple faults when booting the kernel.

I'm puzzled by your exec format error. Are you trying to run something compiled for windows under linux? Perhaps `HOSTCC` also needs to be set to `i386-elf-gcc`?

Can you paste the output of `make`?

**Comment by freewilll** [comment]
I just built and ran it with ubuntu 16.04. It's still working there. For some reason the decompressed image under 20.04 has incorrect data in it, leading to invalid instructions and the triple fault.

**Comment by freewilll** [comment]
I got it to work under ubuntu 20.04 (64 bit). The problem was that some code was being generated before 0x100000. If I add `-fno-reorder-blocks-and-partition` to the compile flags, the problem goes away.

**Comment by freewilll** [comment]
I also got it working under MacOS Monterey. I updated the toolchain to use `x86_64-elf-*` since the i386 version no longer exists in MacOS. I merged my changes into master.

I still don't understand your exec format error. The `Makefile` has this:

```
tools/build: $(CONFIGURE) tools/build.c
	$(HOSTCC) -o tools/build tools/build.c
```

which means that `tools/build` should be executable on the host you are building linux on. Can you paste the output of `make clean && make tools/build`?

**Comment by XEN486** [comment]
hi, sorry for not responding, I will get back to you hopefully soon.

**Comment by XEN486** [comment]
something interesting happened, I did quite literally nothing and it just started compiling! no idea what I did at all so yeah

**Comment by XEN486** [comment]
it also boots so yeah
